### ISSUE TITLE
Search Crashes OS on Nook

### ISSUE THREAD

**Issue by davebush** [geometer/FBReaderJ#58]
Running a search on a rooted Nook causes the OS to crash and re-boot - every time.

**Comment by jgissend10** [comment]
This is still an issue. Are there any plans to fix this?

**Comment by liquiddandruff** [comment]
Does it crash when searching for text within a book or searching for books within the library? Can you give a simple touch by touch reproduction of the bug so we know when exactly it crashes? I will try to look into this a bit but I do not have a Nook.

**Comment by jgissend10** [comment]
It crashes from the library and network library search. It happens when you
go to click search. The nook can't load the search widget and crashes.

**Comment by geometer** [comment]
Really? Do you use build for NST: http://fbreader.org/content/special-editions#nst?

**Comment by jgissend10** [comment]
Yep! That's the one I installed.

**Comment by geometer** [comment]
Ooops. I was sure there is special implementation of search dialog in this package; however I do not see it in the code. :(

**Comment by geometer** [comment]
Oh, no, it's here. :) How do you run search? May be result depends on calling method,

**Comment by jgissend10** [comment]
This is what logcat logs when I click the search button within any book:
```
W/InputManagerService(24097): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@49ea6380

D/dalvikvm(24138): GC freed 1173 objects / 249184 bytes in 48ms

D/EPD#AbsListView(24097): resetRegion 5

D/NATIVE-EPD(24097): epd_reset_region: 0x20

D/EPD#AbsListView(24097): resetRegion 5

D/NATIVE-EPD(24097): epd_reset_region: 0x20

W/InputManagerService(24097): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@49ec02d0

D/EPD#Dialog(24097): set region 2 10 = 0,0 -> 760,1024 = GC

D/NATIVE-EPD(24097): epd_set_region: 2 (0,0,760,1024) 0,0 10

W/dalvikvm(24562): VFY: unable to find class referenced in signature (Landroid/animation/Animator;)

W/dalvikvm(24562): VFY: unable to find class referenced in signature (Landroid/animation/Animator;)

I/dalvikvm(24562): Could not find method android.animation.Animator.end, referenced from method org.geometerplus.android.fbreader.PopupWindow.hideAnimatedInternal

W/dalvikvm(24562): VFY: unable to resolve virtual method 6: Landroid/animation/Animator;.end ()V

D/dalvikvm(24562): VFY: replacing opcode 0x6e at 0x0006

D/dalvikvm(24562): Making a copy of Lorg/geometerplus/android/fbreader/PopupWindow;.hideAnimatedInternal code (128 bytes)

I/dalvikvm(24562): Could not find method org.geometerplus.android.fbreader.PopupWindow.setAlpha, referenced from method org.geometerplus.android.fbreader.PopupWindow.hideAnimatedInternal

W/dalvikvm(24562): VFY: unable to resolve virtual method 9375: Lorg/geometerplus/android/fbreader/PopupWindow;.setAlpha (F)V

D/dalvikvm(24562): VFY: replacing opcode 0x6e at 0x0014

W/dalvikvm(24562): Unable to resolve superclass of Lorg/geometerplus/android/fbreader/PopupWindow$1; (9)

W/dalvikvm(24562): Link of class 'Lorg/geometerplus/android/fbreader/PopupWindow$1;' failed

E/dalvikvm(24562): Could not find class 'org.geometerplus.android.fbreader.PopupWindow$1', referenced from method org.geometerplus.android.fbreader.PopupWindow.initAnimator

W/dalvikvm(24562): VFY: unable to resolve new-instance 1536 (Lorg/geometerplus/android/fbreader/PopupWindow$1;) in Lorg/geometerplus/android/fbreader/PopupWindow;

D/dalvikvm(24562): VFY: replacing opcode 0x22 at 0x0000

D/dalvikvm(24562): Making a copy of Lorg/geometerplus/android/fbreader/PopupWindow;.initAnimator code (48 bytes)

I/dalvikvm(24562): Could not find method android.animation.Animator.end, referenced from method org.geometerplus.android.fbreader.PopupWindow.showAnimatedInternal

W/dalvikvm(24562): VFY: unable to resolve virtual method 6: Landroid/animation/Animator;.end ()V

D/dalvikvm(24562): VFY: replacing opcode 0x6e at 0x0007

D/dalvikvm(24562): Making a copy of Lorg/geometerplus/android/fbreader/PopupWindow;.showAnimatedInternal code (128 bytes)

I/dalvikvm(24562): Could not find method org.geometerplus.android.fbreader.PopupWindow.setAlpha, referenced from method org.geometerplus.android.fbreader.PopupWindow.showAnimatedInternal

W/dalvikvm(24562): VFY: unable to resolve virtual method 9375: Lorg/geometerplus/android/fbreader/PopupWindow;.setAlpha (F)V

D/dalvikvm(24562): VFY: replacing opcode 0x6e at 0x0015

W/dalvikvm(24097): threadid=95: thread exiting with uncaught exception (group=0x4001b170)

E/AndroidRuntime(24097): Uncaught handler: thread SearchDialog exiting due to uncaught exception

E/AndroidRuntime(24097): *** EXCEPTION IN SYSTEM PROCESS.  System will crash.

E/AndroidRuntime(24097): java.lang.NullPointerException

E/AndroidRuntime(24097): 	at android.widget.AutoCompleteTextView.performFiltering(AutoCompleteTextView.java:970)

E/AndroidRuntime(24097): 	at android.app.SearchDialog$SearchAutoComplete.allowFilter(SearchDialog.java:2159)

E/AndroidRuntime(24097): 	at android.app.SearchDialog$1.onTextChanged(SearchDialog.java:998)

E/AndroidRuntime(24097): 	at android.widget.TextView.sendOnTextChanged(TextView.java:6218)

E/AndroidRuntime(24097): 	at android.widget.TextView.setText(TextView.java:2745)

E/AndroidRuntime(24097): 	at android.widget.TextView.setText(TextView.java:2610)

E/AndroidRuntime(24097): 	at android.widget.EditText.setText(EditText.java:81)

E/AndroidRuntime(24097): 	at android.widget.TextView.setText(TextView.java:2585)

E/AndroidRuntime(24097): 	at android.app.SearchDialog.setUserQuery(SearchDialog.java:2343)

E/AndroidRuntime(24097): 	at android.app.SearchDialog.doShow(SearchDialog.java:364)

E/AndroidRuntime(24097): 	at android.app.SearchDialog.show(SearchDialog.java:291)

E/AndroidRuntime(24097): 	at android.server.search.SearchDialogWrapper.performStartSearch(SearchDialogWrapper.java:309)

E/AndroidRuntime(24097): 	at android.server.search.SearchDialogWrapper$SearchDialogHandler.handleStartSearchMessage(SearchDialogWrapper.java:278)

E/AndroidRuntime(24097): 	at android.server.search.SearchDialogWrapper$SearchDialogHandler.handleMessage(SearchDialogWrapper.java:253)

E/AndroidRuntime(24097): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime(24097): 	at android.os.Looper.loop(Looper.java:123)

E/AndroidRuntime(24097): 	at android.os.HandlerThread.run(HandlerThread.java:60)

I/Process (24097): Sending signal. PID: 24097 SIG: 9
```

And this is from the network library screen.
```
I/ActivityManager(24634): Displayed activity org.geometerplus.zlibrary.ui.android/org.geometerplus.android.fbreader.network.NetworkLibraryPrimaryActivity: 1260 ms (total 1260 ms)

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/EPD#Dialog(24634): resetRegion 2

D/NATIVE-EPD(24634): epd_reset_region: 0x04

D/EPD#Dialog(24634): Disable EPD for 100 ms

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/dalvikvm(25081): GC freed 4775 objects / 262560 bytes in 84ms

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

W/InputManagerService(24634): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@49e47310 (uid=10016 pid=24969)

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/EPD#AbsListView(24634): resetRegion 5

D/NATIVE-EPD(24634): epd_reset_region: 0x20

D/EPD#Dialog(24634): set region 2 10 = 0,0 -> 760,1024 = GC

D/NATIVE-EPD(24634): epd_set_region: 2 (0,0,760,1024) 0,0 10

W/dalvikvm(24634): threadid=95: thread exiting with uncaught exception (group=0x4001b170)

E/AndroidRuntime(24634): Uncaught handler: thread SearchDialog exiting due to uncaught exception

E/AndroidRuntime(24634): *** EXCEPTION IN SYSTEM PROCESS.  System will crash.

E/AndroidRuntime(24634): java.lang.NullPointerException

E/AndroidRuntime(24634): 	at android.widget.AutoCompleteTextView.performFiltering(AutoCompleteTextView.java:970)

E/AndroidRuntime(24634): 	at android.app.SearchDialog$SearchAutoComplete.allowFilter(SearchDialog.java:2159)

E/AndroidRuntime(24634): 	at android.app.SearchDialog$1.onTextChanged(SearchDialog.java:998)

E/AndroidRuntime(24634): 	at android.widget.TextView.sendOnTextChanged(TextView.java:6218)

E/AndroidRuntime(24634): 	at android.widget.TextView.setText(TextView.java:2745)

E/AndroidRuntime(24634): 	at android.widget.TextView.setText(TextView.java:2610)

E/AndroidRuntime(24634): 	at android.widget.EditText.setText(EditText.java:81)

E/AndroidRuntime(24634): 	at android.widget.TextView.setText(TextView.java:2585)

E/AndroidRuntime(24634): 	at android.app.SearchDialog.setUserQuery(SearchDialog.java:2343)

E/AndroidRuntime(24634): 	at android.app.SearchDialog.doShow(SearchDialog.java:364)

E/AndroidRuntime(24634): 	at android.app.SearchDialog.show(SearchDialog.java:291)

E/AndroidRuntime(24634): 	at android.server.search.SearchDialogWrapper.performStartSearch(SearchDialogWrapper.java:309)

E/AndroidRuntime(24634): 	at android.server.search.SearchDialogWrapper$SearchDialogHandler.handleStartSearchMessage(SearchDialogWrapper.java:278)

E/AndroidRuntime(24634): 	at android.server.search.SearchDialogWrapper$SearchDialogHandler.handleMessage(SearchDialogWrapper.java:253)

E/AndroidRuntime(24634): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime(24634): 	at android.os.Looper.loop(Looper.java:123)

E/AndroidRuntime(24634): 	at android.os.HandlerThread.run(HandlerThread.java:60)

I/Process (24634): Sending signal. PID: 24634 SIG: 9
```

**Comment by geometer** [comment]
I see. But what is "search button"? "Search" item in the menu?

**Comment by jgissend10** [comment]
Yes. For example either of the two options labeled search in the images
attached.

**Comment by geometer** [comment]
Oops. Attached images?

**Comment by jgissend10** [comment]
I tried to attach them to my email response. I've edited it to link to the
images. Sorry :(

**Comment by geometer** [comment]
Thanks, I see. Will test again on my Nook in a days.

**Comment by jgissend10** [comment]
Awesome! Thank you :)

**Comment by geometer** [comment]
Hmm, it works fine on my old NST. May be this means it does not detect your Nook as Nook. Please check: in Settings dialog, is there 'E-Ink screen settings' (4th item fro top)?

**Comment by jgissend10** [comment]
No I don't see that option.

**Comment by jgissend10** [comment]
Oh! I know what's up! My software version is 1.3.1 and my model is the
BNRV500. I have the glowlight nook but its functioning as a simple touch.
Except for those strings. I'll test to see if it works if I change them in
my system device.prop

**Comment by geometer** [comment]
Ok, then it's clear. I built a test package, could you please install and run it, and then send me the log content? In fact I need 6 lines from 'DEVICE BRAND = ???' to 'DEVICE VERSION = ???'.

http://fbreader.org/~geometer/FBReaderJ_nst.apk

**Comment by jgissend10** [comment]
W/System.err(28450): DEVICE BRAND = nook
W/System.err(28450): DEVICE MODEL = BNRV500
W/System.err(28450): DEVICE MANUFACTURER = BarnesAndNoble
W/System.err(28450): DEVICE DISPLAY = ERD79
W/System.err(28450): DEVICE DEVICE = zoom2
W/System.err(28450): DEVICE VERSION = 1.3.1

**Comment by geometer** [comment]
Ok, I hope this version fixes original issue.

http://fbreader.org/~geometer/FBReaderJ_nst.apk

E-Ink settings section should be available as well.

**Comment by jgissend10** [comment]
Works wonderfully! Thank you so much for your amazing response time and work :)

**Comment by geometer** [comment]
Thank you for your help. By the way, which Nook model do you use? I need this info for the next release ChangeLog.

**Comment by jgissend10** [comment]
The Nook Glowlight, specifically this model: http://www.barnesandnoble.com/u/nook-glowlight-ereader/379004122

**Comment by geometer** [comment]
Great, thanks!
